<a href="https://colab.research.google.com/github/codeson101001/Machine-Learning-Projects/blob/master/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#Numpy supports large multi dimensional arrays and matrixs
#Numpy arrays are space and time effiecnet
#In Python we have lists that serve the purpose of arrays, but they are slow to process.
#NumPy aims to provide an array object that is faster that traditional Python lists.
#Github Repository: https://github.com/numpy/numpy


In [2]:
import numpy as np 
print(np.__version__)

1.18.5


In [3]:
#Create arrays in numpy
#NumPy is used to work with arrays
arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [4]:
#Different dimesion arrays
#0-D
arr = np.array(42)
print(arr,'\n')
#1-D
arr = np.array([1, 2, 3, 4, 5])
print(arr,'\n')
#2-D
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr,'\n') 
#3-D- An array that has 2-D arrays (matrices) as its elements is called 3-D array.
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(arr,'\n') 



42 

[1 2 3 4 5] 

[[1 2 3]
 [4 5 6]] 

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]] 



In [ ]:
#Check the number of dimesions for your numpy array
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim) 

0
1
2
3


In [ ]:
#Here we create a array with 5 dimensions, and verify that it has 5 dimensions
arr = np.array([1, 2, 3, 4], ndmin=5)
print(arr)
print('number of dimensions :', arr.ndim) 

[[[[[1 2 3 4]]]]]
number of dimensions : 5


In [ ]:
#Access Array Elements
#Array indexing is the same as accessing an array element
arr = np.array([1, 2, 3, 4])
print(arr[0]) 

1


In [ ]:
arr = np.array([1, 2, 3, 4])
print(arr[2] + arr[3]) 

7


In [ ]:
#Access 2-D Arrays
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('2nd element in the 1st dim: ', arr[0, 1]) 

2nd element on 1st dim:  2


In [5]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('5th element on 2nd dim: ', arr[1, 4]) 

5th element on 2nd dim:  10


In [ ]:
#Access 3-D Arrays
#Access the third element of the second array of the first array:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr[0, 1, 2]) 

6


arr[0, 1, 2] prints the value 6.

And this is why:

The first number represents the first dimension, which contains two arrays:
[[1, 2, 3], [4, 5, 6]]
and:
[[7, 8, 9], [10, 11, 12]]
Since we selected 0, we are left with the first array:
[[1, 2, 3], [4, 5, 6]]

The second number represents the second dimension, which also contains two arrays:
[1, 2, 3]
and:
[4, 5, 6]
Since we selected 1, we are left with the second array:
[4, 5, 6]

The third number represents the third dimension, which contains three values:
4
5
6
Since we selected 2, we end up with the third value:
6


In [6]:
#Negative Indexing
#Use negative indexing to access an array from the end.
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('Last element from 2nd dim: ', arr[1, -1]) 

Last element from 2nd dim:  10


In [7]:
#NumPy Array Slicing
#Slicing in python means taking elements from one given index to another given index.
#We pass slice instead of index like this: [start:end].
#We can also define the step, like this: [start:end:step].
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5]) 

[2 3 4 5]


In [8]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[4:]) 

[5 6 7]


In [9]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[:4]) 

[1 2 3 4]


In [10]:
#Negative Slicing
#Use the minus operator to refer to an index from the end:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[-3:-1]) 

[5 6]


In [15]:
#STEP
#Use the step value to determine the step of the slicing:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
#From [1,5) print every 2nd number 
print(arr[1:5:2]) 

[2 4]


In [16]:
#Prints out every odd number in th enumpy list
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[::2])

[1 3 5 7]


In [17]:
#Slicing 2-D Arrays
#Looking at the second array, print from index [7,10)
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[1, 1:4]) 

[7 8 9]
