<a href="https://colab.research.google.com/github/codeson101001/Machine-Learning-Projects/blob/master/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
#Numpy supports large multi dimensional arrays and matrixs
#Numpy arrays are space and time effiecnet
#In Python we have lists that serve the purpose of arrays, but they are slow to process.
#NumPy aims to provide an array object that is faster that traditional Python lists.
#Github Repository: https://github.com/numpy/numpy


In [3]:
import numpy as np 
print(np.__version__)

1.18.5


In [4]:
#Create arrays in numpy
#NumPy is used to work with arrays
arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [5]:
#Different dimesion arrays
#0-D
arr = np.array(42)
print(arr,'\n')
#1-D
arr = np.array([1, 2, 3, 4, 5])
print(arr,'\n')
#2-D
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr,'\n') 
#3-D- An array that has 2-D arrays (matrices) as its elements is called 3-D array.
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(arr,'\n') 



42 

[1 2 3 4 5] 

[[1 2 3]
 [4 5 6]] 

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]] 



In [6]:
#Check the number of dimesions for your numpy array
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim) 

0
1
2
3


In [7]:
#Here we create a array with 5 dimensions, and verify that it has 5 dimensions
arr = np.array([1, 2, 3, 4], ndmin=5)
print(arr)
print('number of dimensions :', arr.ndim) 

[[[[[1 2 3 4]]]]]
number of dimensions : 5


In [8]:
#Access Array Elements
#Array indexing is the same as accessing an array element
arr = np.array([1, 2, 3, 4])
print(arr[0]) 

1


In [9]:
arr = np.array([1, 2, 3, 4])
print(arr[2] + arr[3]) 

7


In [10]:
#Access 2-D Arrays
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('2nd element in the 1st dim: ', arr[0, 1]) 

2nd element in the 1st dim:  2


In [11]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('5th element on 2nd dim: ', arr[1, 4]) 

5th element on 2nd dim:  10


In [12]:
#Access 3-D Arrays
#Access the third element of the second array of the first array:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr[0, 1, 2]) 

6


arr[0, 1, 2] prints the value 6.

And this is why:

The first number represents the first dimension, which contains two arrays:
[[1, 2, 3], [4, 5, 6]]
and:
[[7, 8, 9], [10, 11, 12]]
Since we selected 0, we are left with the first array:
[[1, 2, 3], [4, 5, 6]]

The second number represents the second dimension, which also contains two arrays:
[1, 2, 3]
and:
[4, 5, 6]
Since we selected 1, we are left with the second array:
[4, 5, 6]

The third number represents the third dimension, which contains three values:
4
5
6
Since we selected 2, we end up with the third value:
6


In [13]:
#Negative Indexing
#Use negative indexing to access an array from the end.
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('Last element from 2nd dim: ', arr[1, -1]) 

Last element from 2nd dim:  10


**NumPy Array Slicing** 

Slicing arrays

In [14]:
#NumPy Array Slicing
#Slicing in python means taking elements from one given index to another given index.
#We pass slice instead of index like this: [start:end].
#We can also define the step, like this: [start:end:step].
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5]) 

[2 3 4 5]


In [15]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[4:]) 

[5 6 7]


In [16]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[:4]) 

[1 2 3 4]


Negative Slicing

In [17]:
#Negative Slicing
#Use the minus operator to refer to an index from the end:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[-3:-1]) 

[5 6]


Step

In [18]:
#STEP
#Use the step value to determine the step of the slicing:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
#From [1,5) print every 2nd number 
print(arr[1:5:2]) 

[2 4]


In [19]:
#Prints out every odd number in th enumpy list
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[::2])

[1 3 5 7]


Slicing 2-D Arrays

In [20]:
#Slicing 2-D Arrays
#Looking at the second array, print from index [7,10)
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[1, 1:4]) 

[7 8 9]


In [22]:
#From both elements, return index 2:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[0:2, 2])

[3 8]


In [23]:
#From both elements, slice index 1 to index 4 (not included), this will return a 2-D array:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[0:2, 1:4])

[[2 3 4]
 [7 8 9]]


**NumPy Data Types**

Data Types in Python
By default Python have these data types:

strings - used to represent text data, the text is given under quote marks. eg. "ABCD"
integer - used to represent integer numbers. eg. -1, -2, -3
float - used to represent real numbers. eg. 1.2, 42.42
boolean - used to represent True or False.
complex - used to represent a number in complex plain. eg. 1.0 + 2.0j, 1.5 + 2.5j

Data Types in NumPy
NumPy has some extra data types, and refer to data types with one character, like i for integers, u for unsigned integers etc.

Below is a list of all data types in NumPy and the characters used to represent them.

i - integer
b - boolean
u - unsigned integer
f - float
c - complex float
m - timedelta
M - datetime
O - object
S - string
U - unicode string
V - fixed chunk of memory for other type ( void )


In [25]:
#Checking the Data Type of an Array
arr = np.array([1, 2, 3, 4])
print(arr.dtype)

arr = np.array(['apple', 'banana', 'cherry'])
print(arr.dtype)

int64
<U6


Creating Arrays With a Defined Data Type

We use the array() function to create arrays, this function can take an optional argument: dtype that allows us to define the expected data type of the array elements:

In [26]:
arr = np.array([1, 2, 3, 4], dtype='S')
print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [27]:
#For i, u, f, S and U we can define size as well.
arr = np.array([1, 2, 3, 4], dtype='i4')
print(arr)
print(arr.dtype)

[1 2 3 4]
int32


What if a Value Can Not Be Converted?

If a type is given in which elements can't be casted then NumPy will raise a ValueError.

In [31]:
#A non integer string like 'a' can not be converted to integer (will raise an error):
#arr = np.array(['a', '2', '3'], dtype='i')

Converting Data Type on Existing Arrays

The best way to change the data type of an existing array, is to make a copy of the array with the astype() method.

The astype() function creates a copy of the array, and allows you to specify the data type as a parameter.

The data type can be specified using a string, like 'f' for float, 'i' for integer etc. or you can use the data type directly like float for float and int for integer.

In [37]:
#Change data type from float to integer by using 'i' as parameter value:
arr = np.array([1.1, 2.1, 3.9])
newarr = arr.astype('i')
print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [38]:
#Change data type from float to integer by using int as parameter value:
#Each type of integer has a different range of storage capacity
arr = np.array([1.1, 2.1, 3.1])
newarr = arr.astype(int)
print(newarr)
print(newarr.dtype)

[1 2 3]
int64


In [45]:
#Change data type from integer to boolean:
arr = np.array([1, 0, 3, 5, 7, 10,101,-12,1.21123,0.12])
newarr = arr.astype(bool)
print(newarr)
print(newarr.dtype)

[ True False  True  True  True  True  True  True  True  True]
bool


NumPy Array Copy vs View

The Difference Between Copy and View

The main difference between a copy and a view of an array is that the copy is a new array, and the view is just a view of the original array.

The copy owns the data and any changes made to the copy will not affect original array, and any changes made to the original array will not affect the copy.

The view does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view.



In [46]:
#COPY
#Make a copy, change the original array, and display both arrays:
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42
print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [47]:
#VIEW:
#Make a view, change the original array, and display both arrays
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [49]:
#Make a view, change the view, and display both arrays:
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
x[0] = 31

print(arr)
print(x)

[31  2  3  4  5]
[31  2  3  4  5]


**Check if Array Owns it's Data**
As mentioned above, copies owns the data, and views does not own the data, but how can we check this?
Every NumPy array has the attribute base that returns None if the array owns the data.
Otherwise, the base  attribute refers to the original object.

In [50]:
#Print the value of the base attribute to check if an array owns it's data or not:
arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)

None
[1 2 3 4 5]


NumPy Array Shape


In [51]:
#Shape of an Array
#The shape of an array is the number of elements in each dimension.
#Get the Shape of an Array
#NumPy arrays have an attribute called shape that returns a tuple with each index having the number of corresponding elements.
#Print the shape of a 2-D array:
#The example above returns (2, 4), which means that the array has 2 dimensions, and each dimension has 4 elements.

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr.shape)

(2, 4)


In [52]:
#Create an array with 5 dimensions using ndmin using a vector with values 1,2,3,4 and verify that last dimension has value 4:
arr = np.array([1, 2, 3, 4], ndmin=5)
print(arr)
print('shape of array :', arr.shape)

[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)
